config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:show] do
    member do
      get :become
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def become
    sign_in(:user, User.find(params[:id]))
    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlangaRailsExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body class="container">
    <br/>
    <h1>Planga.io Example Rails Application</h1>
    <% if user_signed_in? %>
      <hr/>
      <p>You are signed in as <%= current_user.full_name %></p>
    <% end %>
    <hr/>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h2>Users</h2>

<br/>

<table class="table">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= link_to "Profile", user_path(user) %></td>
        <td>
          <% unless (current_user && current_user == user) %>
            <%= link_to "Sign in as #{user.full_name.split(' ').first}", become_user_path(user) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>User: <%= @user.full_name %></h1>

<p>
  <strong>Bio</strong>
</p>

<p><%= @user.bio %></p>

<%= link_to "All Users", root_path %>